### ISSUE TITLE
Add github icon

### ISSUE THREAD

**Issue by boldijar** [alexbajzat/Cleverbot-Android#3]
[ic_github.zip](https://github.com/alexbajzat/Cleverbot-Android/files/100927/ic_github.zip)

Add this icon to your resources and add it to your toolbar.
When you click it , the app should open your repository URL.

Help
http://developer.android.com/training/appbar/actions.html:
http://stackoverflow.com/questions/3004515/android-sending-an-intent-to-browser-to-open-specific-url

Good luck.

**Comment by alexbajzat** [comment]
Done
